const CAKE_ORDERED = 'CAKE_ORDERED';
const CAKE_RESTOCKED = 'CAKE_RESTOCKED';
const CAKE_SUGAR_UPDATED = 'CAKE_SUGAR_UPDATED';
const ICE_CREAM_ORDERED = 'ICE_CREAM_ORDERED';
const ICE_CREAM_RESTOCKED = 'ICE_CREAM_RESTOCKED';

export {
    CAKE_ORDERED,
    CAKE_RESTOCKED,
    ICE_CREAM_ORDERED,
    ICE_CREAM_RESTOCKED,
    CAKE_SUGAR_UPDATED,
}